import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { ThemeProvider } from "@mui/material";
import materialTheme from "@/providers/materialTheme";
import AppFooter from "@/components/Footer/AppFooter";
import { QueryClientProvider } from "@/providers/QueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primaryBg`}
      >
        <QueryClientProvider>
          <ThemeProvider theme={materialTheme}>
            <Header />
            {children}
            <AppFooter />
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
